project_id = "nnotjvqgejcmutukcwvt"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[edge_runtime]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-form-email]
verify_jwt = false

[functions.send-purchase-form]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.admin-localization]
verify_jwt = true

[functions.process-notifications]
verify_jwt = false

[functions.notification-cron]
verify_jwt = false